[package]
name = "bencode_lib"
version = "0.1.5"
edition = "2024"
description = "Bencode library implementation."
license = "MIT"

[features]
default = ["std"]
std = []

[dependencies]
rand = { version = "0.9.2", optional = true }
